### ISSUE TITLE
fingerprintDelegate must be set before a connection can be created

### ISSUE THREAD

**Issue by Taherismail17** [hankinsoft/SQLProSSHTunnel#1]
Hey, when add the delegate it requires me to return data - I am unsure what I am meant to call to return data in this function:

`func sshTunnel(_ tunnelHelper: SQLProSSHTunnelHelper!, keyForHost host: String!, port: UInt) -> Data! {
 }`

Update: 
Got rid of following error with `tunnel.sshIgnoreHostKey = true`
There is a crash here:
`channel =
        libssh2_channel_direct_tcpip_ex(session,
                                        forwardToHost.UTF8String,
                                        (int)forwardToPort,
                                        "127.0.0.1",
                                        (int)localPort);`

**Comment by hankinsoft** [comment]
Hi! This call would be similar to a fingerprint lookup from your known
hosts file. My application is sandboxed, so I cannot access the known hosts
file and need to store the fingerprint myself. If you return nil for this
method, the fingerprint will be found and the:

    // Set our out error
    * outError = [NSError errorWithDomain: SSHTunnelErrorDomain
                                     code:
SSHTunnelUnknownFingerprintErrorCode
                                 userInfo: userInfo];

error will be raised. If you catch this error, you can save the known hosts
if you wish, then return that host the next time the
tunnelHelper:keyForHost:port:
method is called. If it matches the connection will succeed. So in my
app the routine is something like this:

Try and connect
tunnelHelper:keyForHost:port: - returns nil
error with code SSHTunnelUnknownFingerprintErrorCode  is returned and the
fingerprint is in userInfo.
Get the fingerprint from user info and save it
Reconnect
tunnelHelper:keyForHost:port: - returns the saved fingerprint now
connection success.

Hope that helps out!

**Comment by Taherismail17** [comment]
Thanks for the help.

Running this on iOS I am now getting:

`2018-11-16 13:35:20.771943+1300 test[3724:326952] SSH not attempting publickey (none specified).
2018-11-16 13:35:20.771995+1300 test[3724:326952] SSH Attempting password authentication.
2018-11-16 13:35:20.858130+1300 test[3724:326952] SSH authenticate via username/password success.
2018-11-16 13:35:20.858268+1300 test[3724:326952] SSH Successfully authentication.`

I am trying to create a proxy which I can then connect to locally - 

`Forwarding connection from 127.0.0.1:0 to xxx.xxx:0`

That's what I have - I had to change where the NSLog was printing in order to get it to print.
How can I check if the tunnel is active and whether I can use it as a proxy?

Thanks for your time

**Comment by hankinsoft** [comment]
Hi. You can install telnet via hombrew then run

telnet localhost <port that was used>

From terminal. If you have questions on that let me know. I won’t be able
to get back to you until tomorrow though.

**Comment by Taherismail17** [comment]
Hey,

Thanks - successfully opened the connection on Mac and iOS:

`2018-11-16 15:12:51.572434+1300 test mac[11561:306027] Successfully opened channel on port 8888.
2018-11-16 15:12:51.572728+1300 test mac[11561:306113] Waiting for TCP connection on 127.0.0.1:8888...`

`2018-11-16 15:19:33.874287+1300 test mac[11790:317860] Forwarding connection from 127.0.0.1:8888 to xxx.xxx:22
2018-11-16 15:19:33.875060+1300 test mac[11790:317860] The client at 127.0.0.1:8888 disconnected!`

This then occurs

**Comment by hankinsoft** [comment]
Depending on what you are ssh'ing into, it may disconnect if for example you do not send the correct header bytes. Trying having the ssh tunnel open a telnet port and see if you get a disconnecting when sending data.

**Comment by hankinsoft** [comment]
Were you able to get things working?

**Comment by Taherismail17** [comment]
I haven’t had a chance to look at it again. I tried the telnet and that seemed to disconnect it. I’m looking to make a full VPN from the SSH Tunnel on iOS which may not be viable
